
artifact_dir: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_URL: https://archive.ics.uci.edu/static/public/186/wine+quality.zip
  local_data_file: artifact/data_ingestion/wine_quality.zip
  unzip_dir: artifact/data_ingestion
  ingested_train_dir: artifact/data_ingestion/ingested/train
  ingested_test_dir: artifact/data_ingestion/ingested/test

data_validation:
  root_dir: artifact/data_validation
  unzip_data_dir: artifact/data_ingestion/winequality-red.csv   # adjust to your real path
  STATUS_FILE: artifact/data_validation/status.txt
data_transformation:
  root_dir: artifact/data_transformation
  data_path: artifact/data_ingestion/winequality-red.csv